# Generated by Django 3.1.5 on 2021-02-19 11:35

from django.db import migrations, models
import geolocation_fields.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', geolocation_fields.models.fields.PointField(verbose_name='point')),
            ],
        ),
    ]
