# Generated by Django 3.1.5 on 2021-02-19 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcity_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beacon',
            old_name='longitude',
            new_name='location',
        ),
    ]
