# Generated by Django 3.1.5 on 2021-02-19 12:16

from django.db import migrations
import geolocation_fields.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('smartcity_app', '0002_auto_20210219_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacon',
            name='location',
            field=geolocation_fields.models.fields.PointField(verbose_name='location'),
        ),
    ]
