# Generated by Django 3.1.5 on 2021-02-20 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartcity_app', '0005_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacon',
            name='vehicle_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='smartcity_app.vehicle'),
        ),
    ]
