# Generated by Django 3.1.5 on 2021-02-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcity_app', '0006_beacon_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacon',
            name='beacon_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
