# Generated by Django 3.1.5 on 2021-02-20 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smartcity_app', '0008_auto_20210220_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_station', to='smartcity_app.station')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_station', to='smartcity_app.station')),
            ],
        ),
    ]
