# Generated by Django 3.1.5 on 2021-02-20 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smartcity_app', '0009_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='passenger',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'passenger'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
