# Generated by Django 3.1.5 on 2021-01-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_img', models.ImageField(upload_to='arts/')),
                ('title', models.CharField(max_length=264, unique=True)),
                ('story', models.TextField()),
            ],
        ),
    ]
