# Generated by Django 3.1.5 on 2021-01-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts_app', '0002_auto_20210130_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='date',
            field=models.DateTimeField(auto_now=True, help_text='Do you remember when you made this art'),
        ),
        migrations.AlterField(
            model_name='art',
            name='story',
            field=models.TextField(help_text='Write an interesting story behind this art'),
        ),
    ]
