# Generated by Django 3.1.5 on 2021-01-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts_app', '0003_auto_20210130_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='date',
            field=models.DateField(help_text='Do you remember when you made this art'),
        ),
    ]
