# Generated by Django 3.1.5 on 2021-01-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts_app', '0004_auto_20210130_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='art_img',
            field=models.ImageField(help_text='make it clean and neat. ;) ', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='art',
            name='date',
            field=models.DateField(help_text='Do you remember when you made this art ?'),
        ),
        migrations.AlterField(
            model_name='art',
            name='story',
            field=models.TextField(help_text='Write an interesting story behind this art!'),
        ),
        migrations.AlterField(
            model_name='art',
            name='title',
            field=models.CharField(help_text='Write an attractive title!', max_length=264, unique=True),
        ),
    ]
