# Generated by Django 3.1.5 on 2021-02-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts_app', '0005_auto_20210130_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='write the title of this page!', max_length=264, unique=True)),
                ('body', models.TextField(help_text='Write an interesting text about you here')),
            ],
        ),
    ]
