# Generated by Django 3.1.5 on 2021-02-13 20:28

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('arts_app', '0006_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category Name', max_length=264, unique=True)),
                ('discription', models.TextField(help_text='Write an interesting text about you here')),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='body',
            field=djrichtextfield.models.RichTextField(help_text='Write an interesting text about you here'),
        ),
    ]
