# Generated by Django 3.1.5 on 2021-02-28 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0010_auto_20210228_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_sheet', models.FileField(upload_to='uploads/')),
                ('attendance_status', models.CharField(choices=[('absent', 'Absent'), ('present', 'Present'), ('incomplete', 'Incomplete')], default='absent', max_length=120)),
                ('course_schedule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.courseschedule')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
