# Generated by Django 3.1.5 on 2021-02-28 12:38

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category', max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TargetAudience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Target Audience', max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=256, unique=True, verbose_name='Course Name')),
                ('course_overview', djrichtextfield.models.RichTextField(help_text='Write an overview about the course', verbose_name='Overview')),
                ('course_objective', djrichtextfield.models.RichTextField(help_text='Write the objective of the course', verbose_name='Objective')),
                ('prerequisites', djrichtextfield.models.RichTextField(help_text='Write the Prerequisites of the course', verbose_name='Prerequisites')),
                ('course_img', models.ImageField(help_text='make it clean and neat. ;) ', upload_to='images/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.category')),
                ('target_audience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.targetaudience')),
            ],
        ),
    ]
