# Generated by Django 3.1.5 on 2021-02-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Category', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='targetaudience',
            name='name',
            field=models.CharField(help_text='Target Audience', max_length=255, unique=True),
        ),
    ]
