# Generated by Django 3.1.5 on 2021-02-28 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20210228_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisites_courses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.course'),
        ),
    ]
