# Generated by Django 3.1.5 on 2021-02-28 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_courseschedule_location_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_name', models.CharField(max_length=255, unique=True, verbose_name='Instructor Name')),
                ('course_schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='course.courseschedule', verbose_name='Linked Course Schedule')),
            ],
        ),
    ]
