# Generated by Django 3.1.5 on 2021-02-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_instructor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
