# Generated by Django 3.1.5 on 2021-02-28 16:57

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20210228_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschedule',
            name='schedule_state',
            field=django_fsm.FSMField(choices=[('accepting_nominations', 'Accepting Nominiations'), ('registeration_closed', 'Registeration Closed'), ('started', 'Started'), ('end_batch', 'End Batch')], default='accepting_nominations', max_length=50, protected=True, verbose_name='Schedule Status'),
        ),
    ]
