# Generated by Django 3.1.5 on 2021-02-28 17:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20210228_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseschedule',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Please write the start date of this batch', verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Please write the start date of this batch', verbose_name='Start Date'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(help_text='Please write the start date of this batch', verbose_name='Session Date')),
                ('start_time', models.TimeField(help_text='Session start time', verbose_name='Start time')),
                ('end_time', models.TimeField(help_text='Session end time', verbose_name='End time')),
                ('course_schedule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.courseschedule')),
            ],
        ),
    ]
