# Generated by Django 3.1.5 on 2021-02-27 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itp', '0001_initial'),
        ('emp_entity', '0001_initial'),
        ('userprofile', '0003_auto_20210227_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='entity_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_entity', to='emp_entity.employeeentity', verbose_name='Entity Name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Job_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_jobrole', to='itp.jobrole', verbose_name='Standard ITP Role'),
        ),
    ]
