# Generated by Django 3.1.5 on 2021-02-27 08:14

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_userprofile_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='691971923', max_length=128, region=None, verbose_name='Phone Number'),
        ),
    ]
