# Generated by Django 3.1.5 on 2021-02-27 11:52

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_userprofile_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+48691971923', max_length=128, region=None, verbose_name='Phone Number'),
        ),
    ]
