# Generated by Django 3.1.5 on 2021-02-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_auto_20210227_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='year',
            field=models.CharField(choices=[(2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026')], default=2021, max_length=32),
        ),
    ]
