# Generated by Django 3.1.5 on 2021-02-28 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_auto_20210228_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
    ]
