# Generated by Django 3.1.5 on 2021-02-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_entity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeentity',
            name='entity_code',
            field=models.CharField(max_length=150, unique=True, verbose_name='Entity Code'),
        ),
        migrations.AlterField(
            model_name='employeeentity',
            name='entity_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Entity Name'),
        ),
    ]
