# Generated by Django 3.1.5 on 2021-02-28 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_entity', '0002_auto_20210228_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeentity',
            options={'verbose_name': 'Employee Entity', 'verbose_name_plural': 'Employee Entities'},
        ),
    ]
