# Generated by Django 3.1.5 on 2021-02-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser_app', '0002_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_color',
            field=models.CharField(default='Blue', max_length=32),
        ),
    ]
